name: simplegamelib
description: An easy to use package for 2D HTML5 Canvas games.
version: 0.0.2
author: Davy Mitchell <daftspaniel@gmail.com>
homepage: http://www.divingintodart.com

environment:
  sdk: '>=1.0.0 <2.0.0'
