name: simplegamelib
description: An easy to use package for 2D HTML5 Canvas games.
version: 0.0.5
author: Davy Mitchell <daftspaniel@gmail.com>
homepage: http://divingintodart.blogspot.co.uk/p/simplegamelib-homepage.html
dependencies:
  test: '>=0.12.4 <0.20.0'
environment:
  sdk: '>=1.0.0 <2.0.0'
